apiVersion: apps/v1
kind: Deployment
metadata:
  name: ideas-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ideas-backend
  template:
    metadata:
      labels:
        app: ideas-backend
    spec:
      containers:
        - name: backend
          image: ideas-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: postgres://app:app@ideas-db:5432/ideas
            - name: PORT
              value: "4000"
            - name: CORS_ORIGIN
              value: http://localhost:5173
---
apiVersion: v1
kind: Service
metadata:
  name: ideas-backend
spec:
  selector:
    app: ideas-backend
  ports:
    - port: 4000
      targetPort: 4000
